### ISSUE TITLE
Error: Command failed: /usr/bin/osascript -l JavaScript

### ISSUE THREAD

**Issue by northamerican** [wtfaremyinitials/jxa#4]
Node version: `v8.9.4`
OS: `macOS 10.13.6`

I made a script containing the one in the README example and ran it with `node index.js`.
osa2 works fine but i'd like to use jxa.

The script fails with: 
```
➜  app node index.js
/Users/home/Documents/app/node_modules/blocking-await/index.js:27
        throw result
        ^

Error: Command failed: /usr/bin/osascript -l JavaScript
422:445: execution error: Error on line 17: ReferenceError: Can't find variable: obj (-2700)

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
    at Function.module.exports.loopWhile (/Users/home/Documents/app/node_modules/deasync/index.js:72:22)
    at wait (/Users/home/Documents/app/node_modules/blocking-await/index.js:20:13)
```

not sure how to continue. thanks.

**Comment by yaozhenx** [comment]
Same issue here. This package is not usable at all. Anyone take a look please?
